### ISSUE TITLE
Repeat split not recognized

### ISSUE THREAD

**Issue by jugdemon** [stefalie/cga-parser#1]
The parser misses repeat splits because the value of repeats is "None", while the value "\*" is expected. The type is "*". I switch the query to type instead of value in `p_sub_split_2`. So now `value=args[3].type` is used as input for the `AST` instead of `value=args[3].value`.

This enables me to properly see repeats, but I am not 100% sure that this is a proper fix. @stefalie Could you verify this?

**Comment by stefalie** [comment]
Yes, this looks good. When I coded it, I forgot that tokens like *, /, >, etc. only consist of their type and don't carry any values.

**Comment by jugdemon** [comment]
It is just on my branch, though, it is not changed in master.
